global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoAndroidListViewScrollExample.Models;
global using UnoAndroidListViewScrollExample.Presentation;
global using UnoAndroidListViewScrollExample.DataContracts;
global using UnoAndroidListViewScrollExample.DataContracts.Serialization;
global using UnoAndroidListViewScrollExample.Services.Caching;
global using UnoAndroidListViewScrollExample.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
